### ISSUE TITLE
Parsing of github file link

### ISSUE THREAD

**Issue by JacobRuddiman** [devgpt-labs/devgpt#183]
My prompt is "~perfect_solitaire/game.py. In the solitaire class, create a function that returns every card and the cards' variables"

The full stop after game.py is a grammatical one, and not part of the file. Although this is not a serious issue for people who know this, a clickable selection for relevant files from the repository, or file detection in the prompt that highlights the file and ignores connected grammar or text would solve this I think.

**Comment by tom-lewis-code** [comment]
hey @JacobRuddiman, firstly apologies for the slow reply to this issue! I think this issue will not be solved in our latest update - as the logic surrounding file generation and merging to a pull_request has changed drastically. If the issue persists feel free to re-open, but in the meantime I'll close as I do think this is fixed now! :)

Appreciate the report.
