### ISSUE TITLE
Trained model doesn't stay trained

### ISSUE THREAD

**Issue by DoctorSquareDave** [devgpt-labs/devgpt#218]
1. I have a model, with STATUS: UNTRAINED
2. I click Train Model, confirm
3. Spinner goes for a few seconds
4. Updates to STATUS: TRAINED
5. Refresh page
6. Back to STATUS: UNTRAINED

**Comment by joaoafonsoassumpcao** [comment]
same thing with me

**Comment by mladenkn** [comment]
yeah, I also have this problem

**Comment by JungHoonGhae** [comment]
same here

**Comment by HRA42** [comment]
Hi @DoctorSquareDave @joaoafonsoassumpcao @mladenkn @JungHoonGhae :)

One of the devs will look into this asap. Thanks for reporting. :)

**Comment by mladenkn** [comment]
I have done a little research about this, and it looks like I'm getting a 504 (Gateway Timeout) from the server.

And I also wanted to provide some more context, so here's the request payload.

![image](https://github.com/devgpt-labs/devgpt-releases/assets/23460142/23d5ad85-9e5b-4ee5-8e3c-0ec9841e5248)

**Comment by professorsugoi** [comment]
i thought this looked cool after seeing firebase promo it, but yall got me fucked up if you think imma pay 50 smacks/mo for this 🥴

**Comment by forkurmamuth** [comment]
same for me. i get 504 as well

**Comment by tom-lewis-code** [comment]
hey all! @mladenkn @joaoafonsoassumpcao @JungHoonGhae @forkurmamuth, I appreciate your reports on this! Firstly, sorry for the slow reply.

We've moved away from training on the front-end (to avoid issues like this directly), and moved to a system of doing all logic, preparation and code generation out of the view of the user. With this being said, I'll close the issue as this issue it's self is now talking about a deprecated area.

You'll now just be able to select a repo from your github repos, and prompt :) 

Appreciate the report regardless, thanks again!

**Comment by DoctorSquareDave** [comment]
Thank you!
