### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by LasalJayasinghe** [devgpt-labs/devgpt#222]
I enter the relavant data but nothing happens

**Comment by HRA42** [comment]
Hi @LasalJayasinghe :)

Could you give us more details on this? Where are you trying to enter what relevant data?

**Comment by tom-lewis-code** [comment]
hey @LasalJayasinghe, thank you for your report, sorry but as @HRA42 mentioned, this issue doesn't have enough detail for it to be worked on! If you have any screenshots or added notes I'd happily take a look for you, but in the meantime I'll close this: you're welcome to re-open if any issues persist! :) 

Thank you!
