### ISSUE TITLE
Bug Report: AI Model Training Failure Due to 403 Forbidden Error on POST Request

### ISSUE THREAD

**Issue by JungHoonGhae** [devgpt-labs/devgpt#230]
**Summary**
A POST request aimed at initiating AI model training is consistently failing with a 403 Forbidden status code. This seems to be a critical issue as the AI model training cannot be completed successfully.

**Context (HAR Data)**
Request Method: POST
Status Code: 403 Forbidden
Remote Address: 172.64.149.149
Referrer Policy: strict-origin-when-cross-origin
Script Initiator: A JavaScript file from https://code.devgpt.com/_next/static/chunks/7490-9e3e7a33b0fd59e0.js initiates the request.
Response: {"code":"42501","details":null,"hint":null,"message":"new row violates row-level security policy for table \\"training_log\\""}

**Steps to Reproduce**
Navigate to the AI model training initiation section of the application.
Attempt to start the AI model training process.
Observe the failure of the POST request and the 403 Forbidden status code.

**Expected Results**
The application should successfully send a POST request to initiate AI model training and receive a confirmation of the training start.

**Actual Results**
The POST request fails with a 403 Forbidden status code, and the response indicates a row-level security policy violation for the table "training_log".

**Additional Information**
Authentication: The state of user authentication is not clear from the available data.
Related Features: AI Model Training
Resource Type: fetch with High priority

Suggestions for Fix

1. Investigate the server-side row-level security policy for the "training_log" table that is indicated in the error message.
2. Ensure that the application has the necessary permissions to make POST requests to the training_log table.
3. Check if user authentication factors into this issue, especially given the 403 status code implies a permissions problem.

Given the critical nature of AI model training in the application, this issue should be addressed as a high priority.​​

**Comment by HRA42** [comment]
Hi @JungHoonGhae :)

Thanks for reporting. I think this might be the reason for #218..

@tom-lewis-code @ash-lewis could you look into this?

**Comment by tom-lewis-code** [comment]
hey @JungHoonGhae, thank you for reporting this, and for the really in-depth ticket! If all tickets were written like this one, the dev world would have no more problems.

I think this is now surrounding some deprecated logic, so I will close it, but feel free to re-open if you feel this needs to be looked into.
