### ISSUE TITLE
Client crash on prompt

### ISSUE THREAD

**Issue by jonathanelmgren** [devgpt-labs/devgpt#261]
I'm facing this error upon clicking "enter" in the prompt textarea. It doesn't matter what I type in the textbox:

![Screenshot 2023-11-21 at 12 29 35](https://github.com/devgpt-labs/devgpt/assets/81702447/443ed61d-f648-4c3b-92ca-a51e0f81dda0)

Upon refresh the prompt shows up in my list but is flagged as Error:
![Screenshot 2023-11-21 at 12 30 59](https://github.com/devgpt-labs/devgpt/assets/81702447/4cd73a62-cd73-4bae-b396-25232e4da144)

**Comment by tom-lewis-code** [comment]
hey @jonathanelmgren, I really appreciate this bug report: you're completely correct. I'll look into this immediately and raise a fix.

Edit: I've linked this to the new change we've made to allow tickets to come from Jira.

**Comment by ash-lewis** [comment]
This is now resolved! @jonathanelmgren
