### ISSUE TITLE
30 days trial becomes a 7 days trial. I want a refund, but there's no refund button.

### ISSUE THREAD

**Issue by LeeShuYun** [devgpt-labs/devgpt#268]
Hello dev team, 
I was promised a 30 days trial when I signed up on the 21st December 2023, and it's already charging me only 7 days later on 28th December yesterday. I haven't even got to try it much, only sent 1 single prompt. I don't intend to use this service anymore and 1 prompt for 49USD is very expensive. I would like a refund and a full deletion of any of stored personal data of mine that you have in your database, please. Mailing your support email about this as well. 

![image](https://github.com/devgpt-labs/devgpt/assets/107480969/814eef04-cd3f-4ea2-8560-1aa4c71497c3)
<img width="949" alt="Screenshot 2023-12-29 213509" src="https://github.com/devgpt-labs/devgpt/assets/107480969/815c7c0d-3c6f-4303-a2c9-8851a76db612">

**Comment by CodingDanny** [comment]
Same here!

**Comment by den-vasyliev** [comment]
I cancelled it on the first day, but they still charge me. I've also sent an email asking them to cancel the subscription again.

**Comment by ash-lewis** [comment]
Hi @den-vasyliev @CodingDanny @LeeShuYun Thanks for bringing this to my attention! We typically use discord for all support enquiries. 

We're happy to give refunds in all cases where you didn't enjoy the product. Can you please email support@devgpt.com? I've also just added this to our contact page to make sure future users don't run into this issue. Thanks again for reporting.

**Comment by CodingDanny** [comment]
> Hi @den-vasyliev @CodingDanny @LeeShuYun Thanks for bringing this to my attention! We typically use discord for all support enquiries.
> 
> We're happy to give refunds in all cases where you didn't enjoy the product. Can you please email [support@devgpt.com](mailto:support@devgpt.com)? I've also just added this to our contact page to make sure future users don't run into this issue. Thanks again for reporting.

I did write multiple mails to support@devgpt.com over the last months without any answers.
