### ISSUE TITLE
Ability to dump details of a task for reporting issues

### ISSUE THREAD

**Issue by derick-dsouza** [devgpt-labs/devgpt#28]
This is useful when reporting issues, it should export the entire thread of the task - the prompts/responses/output. If you are storing something under the hood, then dump that as well.

**Comment by tom-lewis-code** [comment]
Hey Derick! Thank you for the report, I really appreciate your thorough testing here. Is there any more detail you can give on this improvement?

I want to make sure you know: we have a discord where you can talk about these issues. I know we would massively appreciate your knowledge in there (if you're not already in!)

**Comment by derick-dsouza** [comment]
Hi Tom, See #29 which I just posted. I had to send a screenshot of my tasks and the follow up prompts and the eventually output. If you could give an ability to dump the task thread then it would avoid the need to capture screenshots. Something like the share option in ChatGPT but just download the files locally. It could be in JSON or any other format that makes it more easy for you to process. The objective here, is to send the file to you to help with troubleshooting.

**Comment by HRA42** [comment]
@tom-lewis-code is this still needed or can we close the issue for now? Should be worked into the reworked local app.
